# Generated by Django 5.0.3 on 2024-03-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewimage',
            old_name='images',
            new_name='image',
        ),
    ]
