# Generated by Django 5.0.3 on 2024-03-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_images_reviewimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_avatar',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
