# Generated by Django 5.0.3 on 2024-03-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('price', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('link', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='', upload_to='media/')),
            ],
        ),
    ]
